package langs

import (
	base "github.com/omo/fuga/base"
)

type CppGenerator struct{}

var cppTemplate = TemplateMap{
	"foo.cpp": `// Generated by fuga
#include <iostream>

int main(int argc, char* argv[]) {
  std::cout << "Hello, World!" << std::endl;
  return 0;
}
`,

	"Makefile": `#
CC=g++
TARGET=./foo
SOURCE=./foo.cpp

run : ${TARGET}
	${TARGET}

clean :
	-rm ${TARGET}

${TARGET} : ${SOURCE}
	${CC} $^ -o $@

.PHONY : run clean
`,
	".gitignore": `
foo
*.o
*.obj
*.exe
`}

func (*CppGenerator) Generate(writer base.StubWriter) error {
	cppTemplate.WriteTo(writer, "foo.cpp")
	cppTemplate.WriteTo(writer, "Makefile")
	cppTemplate.WriteTo(writer, ".gitignore")
	return nil
}

func init() {
	base.AddGenerator("cpp", &CppGenerator{})
}
