package langs

import (
	"flag"
	base "github.com/omo/fuga/base"
)

type CppGenerator struct{}

var cppTemplate = TemplateMap{
	"foo.cpp": `// Generated by fuga
#include <iostream>

int main(int argc, char* argv[]) {
  std::cout << "Hello, World!" << std::endl;
  return 0;
}
`,

	"Makefile": `#
CC={{.CompilerName}}
TARGET=./foo
SOURCE=./foo.cpp

run : $(TARGET)
	$(TARGET)

clean :
	-rm $(TARGET)

$(TARGET) : $(SOURCE)
	$(CC) $^ -o $@

.PHONY : run clean
`,
	".gitignore": `
foo
*.o
*.obj
*.exe
`}

type cppOptions struct {
	CompilerName string
}

func (*CppGenerator) Generate(writer base.StubWriter) error {
	cppTemplate.WriteTo(writer, "foo.cpp")
	cppTemplate.WriteToWith(writer, "Makefile", cppOptions{CompilerName: *givenCppCommpiler})
	cppTemplate.WriteTo(writer, ".gitignore")
	return nil
}

var givenCppCommpiler = flag.String("cpp-compiler", "gcc",
	"generate cpp: C++ compiler.")

func init() {
	base.AddGenerator("cpp", &CppGenerator{})
}
