package langs

import (
	base "github.com/omo/fuga/base"
)

type GoGenerator struct{}

var goTemplate = TemplateMap{
	"foo.go": `// Generated by fuga
package main

import (
	"fmt"
)

var _ = fmt.Printf

func main() {
	fmt.Printf("Hello, World\n")
}
`}

func (*GoGenerator) Generate(writer base.StubWriter) error {
	goTemplate.WriteTo(writer, "foo.go")
	return nil
}

type GoLanguage struct{}

func (*GoLanguage) MakeGenerator() base.StubGenerator {
	return &GoGenerator{}
}

func (*GoLanguage) MakeRunner() base.BuildRunner {
	return nil
}

func init() {
	base.AddLanguage("go", &GoLanguage{})
}
